version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - linkedpurry-db
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    networks:
      - app-network

  linkedpurry-db:
    image: postgres:14-alpine
    container_name: postgres
    hostname: linkedpurry-db
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
