version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Backend berjalan di port 3000
    environment:
      # Variabel lingkungan untuk database dan Redis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Frontend berjalan di port 8080 (nginx default)
    environment:
      # Menentukan URL API backend jika diperlukan
      VITE_BACKEND_URL: http://localhost:3000
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5433:5432" # PostgreSQL berjalan di port 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379" # Redis berjalan di port 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
